import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

import MainTopBar from "@/components/main-layout/main-top-bar/main-top-bar";
import MainHeader from "@/components/main-layout/main-header/main-header";
import InstagramSection from "@/sections/main/instagram";
import NavigationSection from "@/sections/main/navigation";
import MainFooter from "@/components/main-layout/main-footer/main-footer";
import MainPromotional from "@/components/main-layout/main-promotional";

const jostSans = Jost({
  variable: "--font-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${jostSans.variable}  antialiased`}>
        <MainTopBar />
        <MainHeader />
        <MainPromotional />
        {children}
        <InstagramSection />
        <NavigationSection />
        <MainFooter />
      </body>
    </html>
  );
};

export default RootLayout;
